// Extracted from the preserved 2.1.4-alpha baseline; editable application source.
const AUDIO_ELEMENT_FOR_PLAY_RESULT = "audio-result";
const AUDIO_ELEMENT_FOR_PLAY_MONITOR = "audio-monitor";
const AUDIO_ELEMENT_FOR_INPUT_MEDIA = "AUDIO_ELEMENT_FOR_INPUT_MEDIA";
const AUDIO_ELEMENT_FOR_INPUT_MEDIA_ECHOBACK = "AUDIO_ELEMENT_FOR_INPUT_MEDIA_ECHOBACK";
export { AUDIO_ELEMENT_FOR_INPUT_MEDIA, AUDIO_ELEMENT_FOR_INPUT_MEDIA_ECHOBACK, AUDIO_ELEMENT_FOR_PLAY_RESULT, AUDIO_ELEMENT_FOR_PLAY_MONITOR };
